---
# tasks file for ansible-fastnodemanager

- name: Import distro specific variables
  include_vars: '{{ item }}'
  with_first_found:
    - '{{ ansible_os_family }}.yml'
    - default.yml

- name: Install fnm system prerequisites
  action: >
    {{ ansible_pkg_mgr }} name="{{ fnm_required_pkgs }}"
  become: true

- name: Define fnm_user
  set_fact:
    fnm_user: "{{ ansible_user | default(lookup('env', 'USER')) }}"
  when: fnm_user is not defined

- name: Get fnm_user from passwd database
  getent:
    database: passwd
    key: "{{ fnm_user }}"
    split: ":"

- name: Define fnm_user_home
  set_fact:
    fnm_user_home: "{{ getent_passwd[fnm_user][4] }}"

- name: Define fnm_user_shell
  set_fact:
    fnm_user_shell: "{{ getent_passwd[fnm_user][5] }}"

- name: Define fnm_user_shell_rc
  set_fact:
    fnm_user_shell_rc: "{{ item.name }}"
  when:
    - fnm_user_shell|regex_replace('^.*/','') == item.shell
  with_items:
    - name: "{{ fnm_user_home }}/.bashrc"
      shell: "bash"
    - name: "{{ fnm_user_home }}/.zshrc"
      shell: "zsh"

- name: Define fnm_root
  set_fact:
    fnm_root: "{{ getent_passwd[fnm_user][4] }}/{{ fnm_root_suffix }}"
  when: fnm_root is not defined

- name: Install fnm
  import_tasks: "install-fnm.yml"
  become: true
  become_user: "{{ fnm_user }}"
