---
- name: Converge
  hosts: all
  vars:
    fnm_npm_global_packages:
      - name: neovim
    fnm_install_user: "testuser"
  tasks:
    - name: Add user
      user:
        name: "{{ fnm_install_user }}"
        shell: "/bin/bash"

    - name: Run role
      include_role:
        name: ansible-fastnodemanager
